import {Link} from 'react-router-dom';
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Upload,Clock3,FileCheck2,Wallet,TriangleAlert,ReceiptText,Eye,EyeOff} from 'lucide-react';
import {useAuth} from '../main';
import {currency,day,label,type Row} from '../api';
import {useResource,Loading,ErrorBox,PageHead,Badge,Empty} from '../ui';
export function Dashboard(){const {data:d,error,loading}=useResource('/dashboard');const auth=useAuth();const [showOutstanding,setShowOutstanding]=useState(false);if(loading)return <Loading/>;if(error)return <ErrorBox message={error}/>;const max=Math.max(...d.trend.map((x:Row)=>Number(x.total)),1);return <>
 <PageHead eyebrow="BUSINESS AT A GLANCE" title={`Welcome back, ${auth.user.name.split(' ')[0]}`} description={new Date().toLocaleDateString('en-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} actions={<Link className="button" to="/bills?upload=1"><Upload size={17}/>Upload invoice</Link>}/>
 <div className="overview-band"><div><div className="eyebrow">SUPPLIER OUTSTANDING</div><div className="balance-private"><div className="balance-number" aria-live="polite">{showOutstanding?currency(d.outstanding):'RM ••••••'}</div><button type="button" className="balance-eye" aria-label={showOutstanding?'Hide supplier outstanding':'Show supplier outstanding'} aria-pressed={showOutstanding} onClick={()=>setShowOutstanding(x=>!x)}>{showOutstanding?<EyeOff size={20}/>:<Eye size={20}/>}</button></div><p>Across verified and approved supplier bills</p><Link to="/outstanding">Review outstanding balances <ArrowUpRight size={17}/></Link></div><div className="band-stats"><Link to="/bills?status=needs_review"><FileCheck2/><strong>{d.needs_review}</strong><span>Awaiting verification</span></Link><Link to="/bills?payment_status=overdue"><Clock3/><strong>{d.overdue}</strong><span>Overdue invoices</span></Link><Link to="/bills"><ReceiptText/><strong>{d.total_bills}</strong><span>Total supplier bills</span></Link></div></div>
 {(d.missing>0||d.failed>0||d.duplicates>0)&&<div className="attention-strip"><TriangleAlert size={20}/><strong>Worth your attention</strong>{d.missing>0&&<Link to="/expected">{d.missing} expected invoices overdue</Link>}{d.failed>0&&<Link to="/bills?status=processing_failed">{d.failed} processing failed</Link>}{d.duplicates>0&&<Link to="/bills">{d.duplicates} possible duplicates</Link>}</div>}
 <div className="dashboard-grid"><section className="panel review-panel"><div className="section-heading"><div><h2>Your review queue</h2><p>Keep documents moving into verified records.</p></div><Link to="/bills?status=needs_review" className="text-link">View all <ArrowRight size={16}/></Link></div>{d.attention.length?<div className="queue">{d.attention.map((b:Row)=><Link to={'/bills/'+b.id} className="queue-row" key={b.id}><span className="document-icon"><ReceiptText size={21}/></span><div><strong>{b.supplier_name}</strong><small>{b.number||'New upload'} · {day(b.created_at)}</small></div><div className="queue-amount"><strong>{currency(b.total)}</strong><Badge value={b.status}/></div><ArrowUpRight size={17}/></Link>)}</div>:<Empty title="You're all caught up" text="New invoices needing review will appear here."/>}</section>
 <section className="panel"><div className="section-heading"><div><h2>Purchasing trend</h2><p>Verified invoice value · last 6 months</p></div><ChartIcon/></div><div className="bar-chart">{d.trend.map((v:Row)=><div className="bar-col" key={v.month}><div className="bar-track"><div className="bar" style={{height:`${Math.max(Number(v.total)/max*100,2)}%`}} title={currency(v.total)}><span>{currency(v.total)}</span></div></div><span>{v.month}</span></div>)}</div><div className="chart-caption"><span className="legend-square"/>Supplier purchasing in MYR</div></section>
 <section className="panel"><div className="section-heading"><div><h2>Upcoming & overdue</h2><p>Prioritise your next supplier payments.</p></div><Link to="/outstanding" className="text-link">View all <ArrowRight size={16}/></Link></div>{d.due.length?<div className="table-wrap"><table><thead><tr><th>Supplier / invoice</th><th>Due date</th><th className="numeric">Remaining</th></tr></thead><tbody>{d.due.map((b:Row)=><tr key={b.id}><td><Link to={'/bills/'+b.id}><strong>{b.supplier_name}</strong><small>{b.number}</small></Link></td><td><span className={b.payment_status==='overdue'?'overdue-text':''}>{day(b.due_date)}</span></td><td className="numeric">{currency(b.outstanding)}</td></tr>)}</tbody></table></div>:<Empty title="No outstanding payments" text="Verified invoices with a balance will appear here."/>}</section>
 <section className="panel"><div className="section-heading"><div><h2>Recent activity</h2><p>The latest changes across your business.</p></div><Link className="text-link" to="/audit">View trail <ArrowRight size={16}/></Link></div><div className="timeline">{d.activity.map((a:Row)=><div className="timeline-item" key={a.id}><span className="timeline-dot"/><div><strong>{label(a.action)}</strong><p>{a.actor_name}{a.details.number?' · '+a.details.number:''}</p><small>{day(a.created_at)}</small></div></div>)}</div></section></div></>}
function ChartIcon(){return <Wallet size={19} className="muted"/>}
