import React,{createContext,useContext,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Navigate,NavLink,useLocation,Link,useNavigate} from 'react-router-dom';
import {LayoutDashboard,ReceiptText,Building2,Wallet,Clock3,Users,Files,ChartNoAxesCombined,ShieldCheck,Settings,LogOut,Menu,ChevronRight,LockKeyhole,ArrowRight,CalendarDays,FileCheck2,Eye,EyeOff} from 'lucide-react';
import {api,post,setCsrf,type Row} from './api';
import {ErrorBox,Loading,Form,PageHead} from './ui';
import {Dashboard} from './pages/Dashboard';
import {Bills,BillDetail} from './pages/Bills';
import {Directory,SupplierDetail,Payments,Expected,People,Payroll,Documents,Reports,AuditTrail,SettingsPage} from './pages/Modules';
import {EmailStatus} from './pages/EmailStatus';
import './style.css';
import './wastage.css';
import {PEOPLE_ENABLED} from './features';
import {WastageList,WastageDetail,Notifications,NotificationBell} from './pages/Wastage';

const Auth=createContext<Row>({});
export const useAuth=()=>useContext(Auth);
const Toast=createContext<(s:string)=>void>(()=>{});
export const useToast=()=>useContext(Toast);

function Login({onLogin}:{onLogin:(v:Row)=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false);
 return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark" aria-hidden="true">HSG</span>HAJJAH SITI GLOBAL</div><div><div className="eyebrow">YOUR BUSINESS, CONNECTED</div><h1>A clearer view.<br/>A better working day.</h1><p>Bring purchasing, stock care and everyday decisions into one shared workspace.</p><div className="story-list"><span><ReceiptText/>Know what needs attention</span><span><Wallet/>Keep supplier payments in view</span><span><ShieldCheck/>Make every change accountable</span></div></div><small>Business management, built around your team.</small></section><section className="login-form"><div><span className="login-icon"><LockKeyhole size={24}/></span><h2>Welcome back</h2><p>Sign in to your business workspace.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await post('/auth/login',{email,password}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Email address<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<span className="password-input"><input type={showPassword?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(x=>!x)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><ErrorBox message={error}/><button className="button" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={18}/></button></form><small>Access is managed by your business owner.</small></div></section></div>
}
const navigation:{group:string,items:[string,string,typeof LayoutDashboard,string][]}[]=[
 {group:'WORKSPACE',items:[['/','Overview',LayoutDashboard,'dashboard.read']]},
 {group:'PURCHASING',items:[['/bills','Supplier bills',ReceiptText,'bills.create'],['/suppliers','Suppliers',Building2,'suppliers.manage'],['/payments','Payments',Wallet,'payments.manage'],['/outstanding','Outstanding',Clock3,'payments.manage'],['/expected','Expected invoices',FileCheck2,'expected.manage']]},
 {group:'OPERATIONS',items:[['/wastage','Stock wastage',FileCheck2,'bills.create']]},
 {group:'PEOPLE',items:[['/employees','Employees',Users,'employees.manage'],['/payroll','Payroll',CalendarDays,'payroll.manage'],['/payslips','Payslips',Files,'payroll.manage']]},
 {group:'MANAGEMENT',items:[['/documents','Documents',Files,'documents.manage'],['/reports','Reports',ChartNoAxesCombined,'reports.read'],['/audit','Audit trail',ShieldCheck,'audit.read'],['/settings','Settings',Settings,'settings.manage']]}
];
function Shell(){
 const auth=useAuth(),toast=useToast(),location=useLocation();const [open,setOpen]=useState(false);
 const current=navigation.flatMap(g=>g.items).find(i=>i[0]==='/'?location.pathname==='/':location.pathname.startsWith(i[0]));
 useEffect(()=>setOpen(false),[location.pathname]);
 const guard=(permission:string,element:React.ReactNode)=>auth.permissions.includes(permission)?element:<Navigate to="/bills" replace/>;
 return <div className="app-shell"><aside className={'sidebar '+(open?'is-open':'')}><Link className="brand" to={auth.user.role==='BOSS'?'/':'/bills'}><span className="brand-mark" aria-hidden="true">HSG</span><span className="hsg-brand">HAJJAH SITI<span className="brand-sub">GLOBAL</span></span></Link><div className="workspace-switch"><span className="workspace-avatar">HSG</span><div>Dried seafood<small>Business operations</small></div></div><nav>{navigation.map(g=>{if(g.group==='PEOPLE'&&!PEOPLE_ENABLED)return null;const items=g.items.filter(i=>auth.permissions.includes(i[3]));return items.length>0&&<div className="nav-group" key={g.group}><div className="nav-label">{g.group}</div>{items.map(([path,title,Icon])=><NavLink to={path} end={path==='/'} key={path}><Icon size={19}/>{path==='/bills'&&auth.user.role!=='BOSS'?'My invoices':title}</NavLink>)}</div>})}</nav><div className="sidebar-foot"><span className="avatar">{auth.user.name.split(' ').map((n:string)=>n[0]).slice(0,2).join('')}</span><Link to="/account">{auth.user.name}<small>{auth.user.role==='BOSS'?'Business owner':'Staff member'}</small></Link><button aria-label="Sign out" onClick={async()=>{try{await post('/auth/logout');auth.logout()}catch(e){toast((e as Error).message)}}}><LogOut size={18}/></button></div></aside>{open&&<div className="nav-scrim" onClick={()=>setOpen(false)}/>}
 <div className="main-shell"><div className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" onClick={()=>setOpen(!open)} aria-label="Open navigation"><Menu/></button><span>Workspace</span><ChevronRight size={14}/><strong>{current?.[0]==='/bills'&&auth.user.role!=='BOSS'?'My invoices':current?.[1]||'Invoice review'}</strong></div><div className="topbar-right"><span className="private-label"><LockKeyhole size={14}/>{auth.user.email.endsWith('@demo.local')?'Demo workspace':'Private workspace'}</span><NotificationBell/><span className="avatar light">{auth.user.name[0]}</span></div></div><main>
 <Routes><Route path="/wastage" element={<WastageList/>}/><Route path="/wastage/:id" element={<WastageDetail/>}/><Route path="/notifications" element={<Notifications/>}/><Route path="/account" element={<AccountPage/>}/><Route path="/" element={guard('dashboard.read',<Dashboard/>)}/><Route path="/bills" element={<Bills/>}/><Route path="/bills/:id" element={<BillDetail/>}/><Route path="/suppliers" element={guard('suppliers.manage',<Directory/>)}/><Route path="/suppliers/:id" element={guard('suppliers.manage',<SupplierDetail/>)}/><Route path="/payments" element={guard('payments.manage',<Payments/>)}/><Route path="/outstanding" element={guard('payments.manage',<Bills outstanding/>)}/><Route path="/expected" element={guard('expected.manage',<Expected/>)}/><Route path="/employees" element={PEOPLE_ENABLED?guard('employees.manage',<People/>):<Navigate to="/bills" replace/>}/><Route path="/payroll" element={PEOPLE_ENABLED?guard('payroll.manage',<Payroll/>):<Navigate to="/bills" replace/>}/><Route path="/payslips" element={PEOPLE_ENABLED?guard('payroll.manage',<Payroll payslips/>):<Navigate to="/bills" replace/>}/><Route path="/documents" element={guard('documents.manage',<Documents/>)}/><Route path="/reports" element={guard('reports.read',<Reports/>)}/><Route path="/audit" element={guard('audit.read',<AuditTrail/>)}/><Route path="/settings" element={guard('settings.manage',<SettingsPage emailStatus={<EmailStatus/>}/>)}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main><footer className="app-footer">HAJJAH SITI GLOBAL <span>Purchasing · Stock care · Business</span></footer></div></div>
}
function AccountPage(){const toast=useToast(),navigate=useNavigate();return <><PageHead title="Your account" eyebrow="PERSONAL SETTINGS" description="Keep your sign-in details secure."/><section className="panel settings-panel"><h2>Change password</h2><Form fields={[{key:'current_password',label:'Current password',type:'password',required:true,full:true},{key:'new_password',label:'New password (12+ characters)',type:'password',required:true,full:true}]} onCancel={()=>navigate(-1)} onSave={async d=>{await post('/auth/password',d);toast('Password updated. Other sessions have been signed out.')}} submit="Update password"/></section></>}
function App(){const [auth,setAuth]=useState<Row|null>(null),[ready,setReady]=useState(false),[message,setMessage]=useState('');function accept(v:Row){setCsrf(v.csrf);setAuth(v)}useEffect(()=>{api('/auth/me').then(accept).catch(()=>{}).finally(()=>setReady(true));const expire=()=>setAuth(null);window.addEventListener('session-expired',expire);return()=>window.removeEventListener('session-expired',expire)},[]);useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(t)}},[message]);return <Toast.Provider value={setMessage}>{!ready?<Loading/>:!auth?<Login onLogin={accept}/>:<Auth.Provider value={{...auth,logout:()=>setAuth(null)}}><Shell/></Auth.Provider>}{message&&<div className="toast" role="status">{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}>×</button></div>}</Toast.Provider>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
