"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '2c02fbe8132c'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('salary >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_name'), ['name'], unique=False)

    op.create_table('login_attempts',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_key'), ['key'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('payment_terms', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('payroll',
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('basic', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('overtime', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('basic + allowances + overtime >= deductions'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'employee_id')
    )
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_period'), ['period'], unique=False)

    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('documents',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('payments',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_bills',
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=150), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('review', sa.JSON(), nullable=False),
    sa.Column('duplicate_ids', sa.JSON(), nullable=False),
    sa.Column('duplicate_resolution', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total >= 0 AND subtotal >= 0 AND tax >= 0'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_bills', schema=None) as batch_op:
        batch_op.create_index('ix_bill_duplicate', ['supplier_id', 'number'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_submitted_by'), ['submitted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_bills_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('expected_invoices',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['supplier_bills.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expected_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expected_invoices_expected_date'), ['expected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expected_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['supplier_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_created_at'), ['created_at'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['bill_id'], ['supplier_bills.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'bill_id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['supplier_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_bill_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_bill_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_bill_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('expected_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_expected_invoices_expected_date'))
        batch_op.drop_index(batch_op.f('ix_expected_invoices_created_at'))

    op.drop_table('expected_invoices')
    with op.batch_alter_table('supplier_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_bills_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_due_date'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_document_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_bills_created_at'))
        batch_op.drop_index('ix_bill_duplicate')

    op.drop_table('supplier_bills')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_created_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_period'))
        batch_op.drop_index(batch_op.f('ix_payroll_employee_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_created_at'))

    op.drop_table('payroll')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))

    op.drop_table('suppliers')
    op.drop_table('roles')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_key'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_name'))
        batch_op.drop_index(batch_op.f('ix_employees_created_at'))

    op.drop_table('employees')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
