"""payment_corrections"""
from alembic import op
import sqlalchemy as sa

revision = 'c9275c57a8d5'
down_revision = '8a20ab4d'
branch_labels = None
depends_on = None
def upgrade():
    existing={c['name'] for c in sa.inspect(op.get_bind()).get_columns('payments')}
    if 'voided_at' not in existing:
        op.add_column('payments',sa.Column('voided_at',sa.DateTime(timezone=True),nullable=True))
    if 'void_reason' not in existing:
        op.add_column('payments',sa.Column('void_reason',sa.Text(),nullable=False,server_default=''))
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_at')

    # ### end Alembic commands ###
